#database
spring:
  datasource:
    url: jdbc:jtds:sqlserver://localhost:1433/DBCURSO
    username: usrCurso
    password: Anitalavalatina9=
  driverClassName: net.sourceforge.jtds.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
